name: Artifacts

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: foobar
          path: hello.txt
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: foobar
      - run: cat hello.txt
