name: Artifacts

on:
  workflow_dispatch:

jobs:
  bench-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: |
          npm i react react-dom react-script create-react-app
      - uses: actions/upload-artifact@v3
        with:
          name: nodemodules
          path: node_modules
  download:
    needs: [bench-upload]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nodemodules
          path: node_modules
      - run: ls
