name: artifact-basics-v4

on:
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted] # [ubuntu-latest, windows-latest, macos-latest, arm, arm64]
    name: artifact upload on ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - run: |
            mkdir artifact-path
            echo "foo" > artifact-path/hello.txt
            echo "hello there" > artifact-path/world.txt

        - uses: actions/upload-artifact@v4.4.3
          with:
            name: my-artifact-${{ matrix.os }}
            path: artifact-path/*

  download-all-artifacts:
    needs: upload-artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: download all artifacts from ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4 # default to GITHUB_WORKSPACE path
