name: artifact-basics-v3

on:
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # note that arm/arm64 are self hosted runners
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest, arm, arm64]
    name: artifact upload on ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - run: |
            mkdir artifact-path
            echo "foo" > artifact-path/hello.txt
            echo "hello there" > artifact-path/world.txt

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact-${{ matrix.os }}
            path: artifact-path/*

        - run: |
            echo "hello, world" > my-artifact.txt

        - uses: actions/upload-artifact@v3
          with:
            name: another-artifact-${{ matrix.os }}
            path: my-artifact.txt
            
  download-single-artifact:
    needs: upload-artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: single artifact download on ${{ matrix.os }}
    steps:
        - name: check attempt
          run: |
            echo $GITHUB_RUN_ATTEMPT
            if [ "$GITHUB_RUN_ATTEMPT" -eq 2 ]; then
              exit 1
            fi
        - uses: actions/download-artifact@v3
          with:
            name: my-artifact-${{ matrix.os }}
            path: artifact-path
  download-all-artifacts:
    needs: upload-artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: download all artifacts from ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v3
