name: Symlinks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    # Test end-to-end by uploading two artifacts and then downloading them
    - name: Create artifact files
      run: |
        mkdir -p path/to/dir-1
        mkdir -p path/to/dir-2
        mkdir -p path/to/dir-3
        mkdir -p original/
        mkdir -p symlink/
        echo "Lorem ipsum dolor sit amet" > path/to/dir-1/file1.txt
        echo "Hello world from file #2" > path/to/dir-2/file2.txt
        echo "Hello from a symlinked file" > original/file.txt
        ln -s original/file.txt symlink/file.txt

    # Upload a symlinked file
    - name: 'Upload symlinked artifact'
      uses: actions/download-artifact@robherley/testing-artifact-2.1.10
      with:
        name: 'Symlinked-Artifact-${{ matrix.runs-on }}'
        path: symlink/file.txt

    - name: 'Download symlinked artifact'
      uses: actions/download-artifact@v4
      with:
        name: 'Symlinked-Artifact-${{ matrix.runs-on }}'
        path: from/symlink

    - name: 'Verify symlinked artifact'
      run: |
        $file = "from/symlink/file.txt"
        if(!(Test-Path -path $file))
        {
            Write-Error "Expected file does not exist"
        }
        if(!((Get-Content $file) -ceq "Hello from a symlinked file"))
        {
            Write-Error "File contents of downloaded artifact are incorrect"
        }
      shell: pwsh
